### PR TITLE
- removed superfluous semicolons from namespace definitions

### PR DESCRIPTION
**Pull request by kratz00**

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
Hmm, I'm going to hold of merging this for a while.

I'm quite happy to merge the change, but you seem to be contributing a bunch of cosmetic changes. Whilst I do agree with this change, I'd rather wait to see what all you come up with and bundle the cosmetic changes together into one large commit; instead of having the git history littered with commits that do not alter the operation of the software.

**Comment by kratz00** [comment]
Personally, I do like small and independent commits, that change one thing at a time.
I am not sure why you are afraid of having multiple commits.
Or is it because of the merge commits?
I can relate to that, they don't look nice but this is the GitHub workflow :smile:

**Comment by Benjamin-Dobell** [comment]
> Personally, I do like small and independent commits, that change one thing at a time.

So do I, but these commits don't really *change* anything, not from the perspective of the software. Having the ability to go back in time and check-out these cosmetic change commits provides no value - they just create noise when someone is legitimately looking at a project's history.

Generally speaking, a commit should encompass an independent *body of work*. Namely a self-contained *set* of changes that in some way that add to or enhance a project.

Improving code quality does indeed enhance a project, but individual changes are neither a *set* or a *body of work*. A developer who sets themselves the task of cleaning up their own codebase would not go through their own codebase and individually treat each and every minor change they make (having the ability to checkout individual changes provides no value). They'd group the changes as into a commit like "Improved project code consistency", "Fixed several typos through-out the code-base", "Refactored <blah>". Within reason, I see no reason why one should treat someone else's codebase any differently from their own.

Yes, from time to time you will see a developer commit "Fixed a typo" or similar. Technically these are a bad habit, they only occur as a result of not following other development best practices (admittedly I'm definitely a culprit of that). However, these commits still only occur from time to time when one unintentionally discovered issues during the course of working on an actual body of work. I merged your previous commits on the pretence that these were simply odd commits - however judging by the timing and quantity that does not seem to be the case.

If one has the task (or has set themselves the task) of cleaning up a code-base, as seems to be the case here, then these *set* of changes should be included as one commit.

> I am not sure why you are afraid of having multiple commits.

*afraid* is a strangely inflammatory word choice. If you would like to contribute to this project then you're welcome to. However, as I am the maintainer of this project, if you wish your changes to be merged then I urge you to show some respect.

> Or is it because of the merge commits?
> I can relate to that, they don't look nice but this is the GitHub workflow :smile:

These commits only appear when merging using the Github web UI. They can trivially be averted by simply checking out your changes locally and fast-forward merging. I haven't bothered doing that for any of your pull requests yet because they're all (with the exception of memory leaks) cosmetic in nature and clearly don't alter the function of the software.

**Comment by kratz00** [comment]
> >  Personally, I do like small and independent commits, that change one thing at a time.

> So do I, but these commits don't really change anything, not from the perspective of the software. Having the ability to go back in time and check-out these cosmetic change commits provides no value - they just create noise when someone is legitimately looking at a project's history.

I get your point and disagree at the same time :smile:
Even a cosmetic change can have unknown side effects, therefor I prefer commits as small as possible, which makes it easier to find problems.

> Generally speaking, a commit should encompass an independent body of work. Namely a self-contained set of changes that in some way adds to or enhances a project.
> 
> Improving code quality does indeed enhance a project, but individual changes are neither a set or a body of work.

In this example here, removing all the superfluous semicolons, this is a body of work in my opinion.
Just removing them for one class and doing one commit for each of the classes would not be according to my understanding. Therefor I think every commit which qualifies and improves the product value make sense to me.

> A developer who sets themselves the task of cleaning up their own codebase would not go through their own codebase and individually treat each and every minor change they make as a separate commit (having the ability to checkout these individual changes provides no value). 

Actually that is how I operate.  For instance I fix one type of compiler warning (for the whole project) and then I do one commit. I will not fix two or more different types and commit them in one big commit. I was just applying my personal standards to your project.


> >    I am not sure why you are afraid of having multiple commits.
> 
> afraid is a strangely inflammatory word choice. If you would like to contribute to this project then you're welcome to. However, as I am the maintainer of this project, if you wish your changes to be merged then I urge you to show some respect.

Sorry about my choice of words, English is not my native language, I did not mean any harm.
Now I know how you feel about having this kind of commits.

Thanks for explaining how you feel about contributing to this project. Would it be a could idea to document this for other people who would like to contribute?

At the moment I have not planed any other changes, so feel free to merge this pull request, if you like, no need to wait :smile:

**Pull request merged**
